[build]
  functions = "functions/"
  command = "sed -i \"s|HOST_URL|${HOST_URL}|g\" netlify.toml && yarn build"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "HOST_URL"